/**
 * @ai-context DevOps Persona - Infrastructure and deployment preparation
 * @ai-invariant DevOps must prepare infrastructure and deployment pipeline
 * @ai-connection DevOps connects to security approval and provides deployment readiness
 */
const BasePersona = require('./base-persona');

class DevOps extends BasePersona {
    constructor(githubToken) {
        super('DevOps Agent', 'DevOps', githubToken);
    }

    async execute(deploymentIssueNumber) {
        this.log('Starting deployment preparation');
        
        try {
            const issue = await this.octokit.rest.issues.get({
                owner: process.env.GITHUB_OWNER || 'helton-godoy',
                repo: process.env.GITHUB_REPO || 'shantilly-cli',
                issue_number: deploymentIssueNumber
            });

            this.updateActiveContext(`Preparando deployment da issue #${deploymentIssueNumber}`);

            // Infrastructure setup
            const infrastructureSetup = await this.setupInfrastructure();
            
            // CI/CD pipeline
            const pipelineConfig = await this.configureCICD();
            
            // Monitoring setup
            const monitoringConfig = await this.setupMonitoring();

            const deploymentReport = this.generateDeploymentReport(infrastructureSetup, pipelineConfig, monitoringConfig);

            await this.microCommit('DevOps: Deployment preparation completed', [
                {
                    path: '.github/workflows/ci-cd.yml',
                    content: pipelineConfig
                },
                {
                    path: 'docs/deployment/deployment-guide.md',
                    content: deploymentReport
                }
            ]);

            await this.createReleaseIssue(issue.data, deploymentReport);

            this.log('Deployment preparation completed');
            return deploymentReport;

        } catch (error) {
            this.log(`Error in DevOps execution: ${error.message}`);
            throw error;
        }
    }

    async setupInfrastructure() {
        return {
            environment: 'Production ready',
            database: 'File-based storage',
            caching: 'In-memory cache',
            monitoring: 'Configured',
            backup: 'Git-based'
        };
    }

    async configureCICD() {
        return `name: BMAD CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    - run: npm ci
    - run: npm test
    - run: npm run lint

  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run security scan
      run: npm audit

  deploy:
    needs: [test, security]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - name: Deploy
      run: echo "Deployment step"`;
    }

    async setupMonitoring() {
        return {
            logging: 'Winston configured',
            metrics: 'Prometheus ready',
            alerts: 'Email notifications',
            healthChecks: 'Endpoint configured'
        };
    }

    generateDeploymentReport(infrastructure, pipeline, monitoring) {
        return `# Deployment Report

## Infrastructure Setup
- **Environment**: ${infrastructure.environment}
- **Database**: ${infrastructure.database}
- **Caching**: ${infrastructure.caching}
- **Monitoring**: ${infrastructure.monitoring}
- **Backup**: ${infrastructure.backup}

## CI/CD Pipeline
- **Test**: Automated testing configured
- **Security**: Security scanning enabled
- **Deploy**: Automated deployment on main branch

## Monitoring Configuration
- **Logging**: ${monitoring.logging}
- **Metrics**: ${monitoring.metrics}
- **Alerts**: ${monitoring.alerts}
- **Health Checks**: ${monitoring.healthChecks}

## Deployment Status
✅ Ready for release

---
*Generated by DevOps Agent on ${new Date().toISOString()}*`;
    }

    async createReleaseIssue(originalIssue, deploymentReport) {
        const title = `Release: ${originalIssue.title.replace('Deployment Preparation: ', '')}`;
        const body = `## Deployment Report
${deploymentReport}

## Release Checklist
- [ ] Version bump
- [ ] Release notes
- [ ] Tag creation
- [ ] Deployment verification

## Next Steps
@helton-godoy/release-manager Please manage release.

---
*Created by DevOps Agent*`;

        await this.createIssue(title, body, ['release', 'deployment']);
    }
}

module.exports = DevOps;
